# Generated by Django 5.1.7 on 2025-04-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='audio_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
