# Generated by Django 5.1.7 on 2025-05-16 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0005_sentence_user_word_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PronunciationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('expected_text', models.TextField()),
                ('word_scores', models.JSONField()),
                ('phoneme_scores', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.sentence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
