# Generated by Django 5.1.7 on 2025-05-26 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0006_pronunciationresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='phonemes',
            field=models.TextField(null=True),
        ),
    ]
