# Generated by Django 4.2.11 on 2025-06-10 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0008_client_remove_sentence_user_profile_sentence_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='has_generated_sentences',
            field=models.BooleanField(default=False),
        ),
    ]
